/* Aussagen: [Kategorie, Aussage, istWahr, Erklärung] */
const QUESTIONS = [["wissen","Wasser kocht auf Meereshöhe bei normalem Luftdruck bei rund 100 °C.",true,"Genau genommen liegt der Siedepunkt bei etwa 99,97 °C, gerundet also bei 100 °C."],
 ["geo","Die Hauptstadt von Australien ist Sydney.",false,"Die Hauptstadt ist Canberra."],
 ["geo","Bern ist die Bundesstadt der Schweiz und Sitz der Bundesbehörden.",true,"Die Verfassung nennt keine Hauptstadt, Bern ist offiziell die Bundesstadt."],
 ["wissen","Oktopusse haben drei Herzen.",true,"Zwei Kiemenherzen und ein Systemherz."],
 ["wissen","Blitze schlagen nie zweimal an derselben Stelle ein.",false,"Hohe Objekte wie Türme werden oft mehrfach getroffen."],
 ["geo","Die Chinesische Mauer ist mit bloßem Auge deutlich aus dem Weltall zu sehen.",false,"Aus dem Orbit ist sie mit bloßem Auge praktisch nicht zu erkennen."],
 ["wissen","Die Venus ist der heißeste Planet im Sonnensystem.",true,"Ihre dichte CO₂-Atmosphäre erzeugt einen extremen Treibhauseffekt, heißer als Merkur."],
 ["wissen","Der Mond ist ein Planet.",false,"Der Mond ist ein Himmelskörper, der die Erde umkreist, also ein Mond."],
 ["wissen","Bananen sind botanisch gesehen Beeren.",true,"Botanisch erfüllen sie die Definition einer Beere."],
 ["wissen","Goldfische haben ein Gedächtnis von nur wenigen Sekunden.",false,"Sie können sich über Wochen und Monate etwas merken."],
 ["wissen","Fledermäuse sind blind.",false,"Fledermäuse können sehen, viele orientieren sich zusätzlich per Echoortung."],
 ["wissen","Haie sind Säugetiere.",false,"Haie sind Knorpelfische."],
 ["wissen","Delfine sind Säugetiere.",true,"Sie atmen Luft und säugen ihre Jungen."],
 ["geo","Der Pazifik ist der größte Ozean der Erde.",true,"Er bedeckt rund ein Drittel der Erdoberfläche."],
 ["geo","Die Sahara ist die größte Wüste der Erde.",false,"Die größte Wüste ist die Antarktis (Kältewüste). Die Sahara ist die größte Heißwüste."],
 ["wissen","Der Mensch nutzt nur 10 % seines Gehirns.",false,"Das ist ein Mythos. Bildgebende Verfahren zeigen Aktivität im ganzen Gehirn."],
 ["his","Die Berliner Mauer fiel im Jahr 1989.",true,"Am 9. November 1989 wurde die Grenze geöffnet."],
 ["his","Das Grundgesetz der Bundesrepublik Deutschland trat im Jahr 1949 in Kraft.",true,"Verkündet am 23. Mai, in Kraft seit dem 24. Mai 1949."],
 ["wissen","Albert Einstein bekam den Nobelpreis für die Relativitätstheorie.",false,"Er erhielt ihn 1921 für die Entdeckung des Gesetzes des photoelektrischen Effekts."],
 ["wissen","Wale sind Fische.",false,"Wale sind Säugetiere."],
 ["wissen","Licht ist schneller als Schall.",true,"Licht ist rund 870.000-mal schneller als Schall in Luft."],
 ["wissen","Auf der Venus dauert ein Tag länger als ein Jahr.",true,"Die Venus dreht sich so langsam, dass ihre Rotation länger dauert als ein Umlauf um die Sonne."],
 ["wissen","Spinnen sind Insekten.",false,"Spinnen sind Spinnentiere mit acht Beinen."],
 ["wissen","Die Sonne ist ein Stern.",true,"Sie ist der uns nächste Stern."],
 ["geo","Die Vatikanstadt ist der kleinste Staat der Welt.",true,"Sie ist sowohl flächen- als auch bevölkerungsmäßig der kleinste anerkannte Staat."],
 ["his","Wikinger trugen Helme mit Hörnern.",false,"Dafür gibt es keine archäologischen Belege. Das Bild stammt aus dem 19. Jahrhundert."],
 ["his","Die Titanic sank im Jahr 1912.",true,"Sie sank in der Nacht vom 14. auf den 15. April 1912."],
 ["wissen","Kaffeebohnen sind botanisch gesehen Samen.",true,"Es sind die Samen der Kaffeekirsche."],
 ["wissen","Der Mars hat zwei Monde.",true,"Phobos und Deimos."],
 ["wissen","Pinguine leben natürlicherweise am Nordpol.",false,"Pinguine leben fast nur auf der Südhalbkugel, am Nordpol gibt es keine."],
 ["his","Napoleon war für seine Zeit ungewöhnlich klein.",false,"Er hatte etwa Durchschnittsgröße. Der Mythos entstand durch Missverständnisse bei Maßeinheiten und Karikaturen."],
 ["wissen","Honigbienen sterben in der Regel, nachdem sie ein Säugetier gestochen haben.",true,"Der Stachel mit Widerhaken bleibt in der Haut stecken."],
 ["wissen","Ein erwachsener Mensch hat 206 Knochen.",true,"Bei Babys sind es mehr, viele wachsen später zusammen."],
 ["geo","Die Zugspitze ist der höchste Berg Deutschlands.",true,"Sie liegt in den Bayerischen Alpen an der Grenze zu Österreich."],
 ["geo","Der Rhein fließt durch Berlin.",false,"Durch Berlin fließen Spree und Havel."],
 ["geo","Die Hauptstadt von Kanada ist Toronto.",false,"Die Hauptstadt ist Ottawa."],
 ["geo","Die Hauptstadt von Brasilien ist Brasília.",true,"Nicht Rio de Janeiro oder São Paulo, Brasília wurde als Hauptstadt neu gebaut."],
 ["geo","Die Hauptstadt der Türkei ist Istanbul.",false,"Die Hauptstadt ist Ankara."],
 ["geo","Der Kilimandscharo liegt in Tansania.",true,"Er ist der höchste Berg Afrikas."],
 ["geo","Afrika ist der flächenmäßig größte Kontinent.",false,"Asien ist der größte Kontinent."],
 ["geo","Russland liegt komplett in Europa.",false,"Der größte Teil des Landes liegt in Asien."],
 ["wissen","Kängurus sind in Australien heimisch.",true,"Sie leben dort natürlicherweise, ebenso auf Neuguinea."],
 ["wissen","Koalas sind eine Bärenart.",false,"Koalas sind Beuteltiere."],
 ["wissen","Der Blauwal ist das größte heute lebende Tier.",true,"Er übertrifft auch die größten Landtiere deutlich."],
 ["wissen","Strauße stecken bei Gefahr den Kopf in den Sand.",false,"Das ist ein Mythos. Sie legen sich flach auf den Boden oder rennen weg."],
 ["wissen","Chamäleons wechseln ihre Farbe vor allem zur Tarnung.",false,"Die Farbe dient vor allem der Kommunikation und der Temperaturregulierung."],
 ["wissen","Bei Seepferdchen tragen die Männchen die Jungen aus.",true,"Die Weibchen legen die Eier in die Bruttasche des Männchens."],
 ["wissen","Wenn man einen Regenwurm teilt, werden daraus zwei Würmer.",false,"Höchstens das Vorderende kann unter Umständen überleben, zwei Würmer entstehen nicht."],
 ["wissen","Honigbienen verständigen sich über einen Schwänzeltanz.",true,"Damit zeigen sie Richtung und Entfernung einer Futterquelle an."],
 ["wissen","Schmetterlinge können mit ihren Füßen schmecken.",true,"Sie haben dort Geschmackssinneszellen."],
 ["wissen","Hunde sehen nur Schwarz und Weiß.",false,"Hunde sehen Farben, aber weniger als Menschen, vor allem Blau und Gelb."],
 ["wissen","Stiere werden wütend, weil das Tuch des Toreros rot ist.",false,"Sie reagieren auf die Bewegung des Tuchs, nicht auf die Farbe."],
 ["wissen","Kamele speichern in ihren Höckern Wasser.",false,"In den Höckern ist Fett gespeichert."],
 ["wissen","Eulen können ihren Kopf um volle 360 Grad drehen.",false,"Sie schaffen etwa 270 Grad."],
 ["wissen","Flamingos sind von Geburt an rosa.",false,"Junge Flamingos sind grau. Die rosa Farbe kommt von Farbstoffen in der Nahrung."],
 ["wissen","Große Pandas ernähren sich fast ausschließlich von Bambus.",true,"Sie sind trotzdem zoologisch Raubtiere."],
 ["wissen","Eisbären haben schwarze Haut unter dem weißen Fell.",true,"Die dunkle Haut nimmt Wärme besser auf."],
 ["wissen","Lemminge stürzen sich als Massenselbstmord von Klippen.",false,"Das ist ein Mythos, der auch durch einen Film von 1958 verbreitet wurde."],
 ["wissen","Kolibris können rückwärts fliegen.",true,"Sie können anhaltend rückwärts fliegen, was bei Vögeln sehr ungewöhnlich ist."],
 ["wissen","Giraffen haben sieben Halswirbel, genau wie Menschen.",true,"Bei Giraffen sind sie extrem lang."],
 ["wissen","Schnecken haben Zähne.",true,"Ihre Raspelzunge, die Radula, ist mit vielen kleinen Zähnchen besetzt."],
 ["wissen","Vögel stammen von Dinosauriern ab.",true,"Sie gelten als lebende Nachfahren der Theropoden."],
 ["wissen","Menschen und Dinosaurier lebten zur selben Zeit.",false,"Die Dinosaurier starben vor etwa 66 Millionen Jahren aus, lange vor dem Menschen."],
 ["wissen","Tomaten sind botanisch gesehen Beeren.",true,"Sie entwickeln sich aus dem Fruchtknoten einer Blüte und haben viele Samen."],
 ["wissen","Kartoffeln gehören zu den Nachtschattengewächsen.",true,"Sie sind mit Tomate und Aubergine verwandt."],
 ["wissen","Erdnüsse sind botanisch gesehen Nüsse.",false,"Erdnüsse sind Hülsenfrüchte."],
 ["wissen","Mandeln sind botanisch gesehen Nüsse.",false,"Die Mandel ist der Samen einer Steinfrucht."],
 ["wissen","Die Haut ist das größte Organ des Menschen.",true,"Sie ist auch das schwerste Organ."],
 ["wissen","Haare und Fingernägel wachsen nach dem Tod weiter.",false,"Die Haut trocknet aus und zieht sich zurück, dadurch wirken sie länger."],
 ["wissen","Venenblut ist blau.",false,"Blut ist immer rot, sauerstoffarmes Blut ist nur dunkler."],
 ["wissen","Die Zunge hat feste Zonen für süß, salzig, sauer und bitter.",false,"Alle Geschmacksrichtungen können auf der gesamten Zunge wahrgenommen werden."],
 ["wissen","Ein Erwachsener hat normalerweise 32 Zähne, wenn alle Weisheitszähne vorhanden sind.",true,"Das ist das vollständige bleibende Gebiss."],
 ["wissen","Die Erde ist eine perfekte Kugel.",false,"Sie ist an den Polen leicht abgeplattet."],
 ["wissen","Auf dem Mond gibt es Wind.",false,"Der Mond hat keine nennenswerte Atmosphäre."],
 ["wissen","Saturn ist der einzige Planet mit Ringen.",false,"Auch Jupiter, Uranus und Neptun haben Ringe."],
 ["wissen","Jupiter ist der größte Planet im Sonnensystem.",true,"Er ist ein Gasriese."],
 ["wissen","Der Merkur ist der sonnennächste Planet.",true,"Er umkreist die Sonne in kürzester Entfernung."],
 ["wissen","Pluto gilt seit 2006 als Zwergplanet.",true,"Die Internationale Astronomische Union hat ihn damals neu eingestuft."],
 ["wissen","Neil Armstrong war der erste Mensch auf dem Mond.",true,"Er betrat ihn im Jahr 1969 bei der Mission Apollo 11."],
 ["wissen","Juri Gagarin war der erste Mensch im Weltall.",true,"Sein Flug fand im Jahr 1961 statt."],
 ["wissen","Ein Lichtjahr ist eine Zeiteinheit.",false,"Es ist eine Längeneinheit, die Strecke, die das Licht in einem Jahr zurücklegt."],
 ["wissen","Sternschnuppen sind verglühende Sterne.",false,"Es sind kleine Staub- und Gesteinsteilchen, die in der Atmosphäre verglühen."],
 ["wissen","Das chemische Symbol für Gold ist Au.",true,"Es kommt vom lateinischen Wort aurum."],
 ["wissen","Das chemische Symbol für Silber ist Si.",false,"Silber hat das Symbol Ag, Si steht für Silicium."],
 ["wissen","Die Luft besteht überwiegend aus Sauerstoff.",false,"Den größten Anteil hat Stickstoff, Sauerstoff macht etwa ein Fünftel aus."],
 ["wissen","Diamant und Graphit bestehen beide aus Kohlenstoff.",true,"Sie unterscheiden sich in der Anordnung der Atome."],
 ["wissen","Schall breitet sich auch im Vakuum aus.",false,"Schall braucht ein Medium wie Luft, Wasser oder einen Festkörper."],
 ["wissen","Eis schwimmt auf Wasser, weil es weniger dicht ist als flüssiges Wasser.",true,"Beim Gefrieren dehnt sich Wasser aus."],
 ["wissen","Donner entsteht durch die schlagartige Ausdehnung der erhitzten Luft im Blitzkanal.",true,"Die Luft dehnt sich so schnell aus, dass eine Druckwelle entsteht."],
 ["geo","Das Tote Meer liegt am tiefsten Punkt der Erdoberfläche an Land.",true,"Sein Ufer liegt weit unter dem Meeresspiegel."],
 ["his","Kolumbus erreichte im Jahr 1492 auf seiner ersten Reise die Karibik.",true,"Wikinger waren schon rund 500 Jahre früher in Nordamerika, Kolumbus war also nicht der erste Europäer dort."],
 ["his","Die Französische Revolution begann im Jahr 1789.",true,"Der Sturm auf die Bastille war am 14. Juli 1789."],
 ["his","Deutschland wurde im Jahr 1990 wiedervereinigt.",true,"Der Beitritt der DDR erfolgte am 3. Oktober 1990."],
 ["his","Die Pyramiden von Gizeh wurden von Sklaven gebaut.",false,"Archäologische Funde zeigen, dass dort bezahlte Arbeiter mit Versorgung arbeiteten."],
 ["his","Kleopatra lebte zeitlich näher an der Mondlandung als am Bau der Cheops-Pyramide.",true,"Zwischen Cheops-Pyramide und Kleopatra liegen rund 2500 Jahre, zwischen Kleopatra und Apollo 11 rund 2000 Jahre."],
 ["his","Gutenberg erfand im 15. Jahrhundert den Buchdruck mit beweglichen Lettern in Europa.",true,"Seine Bibel entstand um 1455 in Mainz."],
 ["his","Der Euro wurde als Bargeld im Jahr 2002 eingeführt.",true,"Als Buchgeld gab es ihn schon seit 1999."],
 ["his","Deutschland hat 16 Bundesländer.",true,"Drei davon sind Stadtstaaten: Berlin, Hamburg und Bremen."],
 ["his","Das Bundesverfassungsgericht hat seinen Sitz in Karlsruhe.",true,"Dort sitzt es seit seiner Gründung."],
 ["his","Von 1949 bis 1990 war Berlin die Hauptstadt der Bundesrepublik.",false,"Bonn war in dieser Zeit Sitz der Bundesorgane und Regierungssitz."],
 ["allg","Goethe schrieb den Faust.",true,"Faust I erschien 1808, Faust II wurde nach seinem Tod veröffentlicht."],
 ["allg","Schiller schrieb den Faust.",false,"Der Autor ist Johann Wolfgang von Goethe."],
 ["allg","Die Mona Lisa hängt im Louvre in Paris.",true,"Gemalt hat sie Leonardo da Vinci."],
 ["allg","Ludwig van Beethoven war von Geburt an taub.",false,"Er verlor sein Gehör erst im Erwachsenenalter."],
 ["allg","Das Internet und das World Wide Web sind dasselbe.",false,"Das Web ist nur ein Dienst, der das Internet nutzt."],
 ["allg","Das World Wide Web wurde von Tim Berners-Lee am CERN entwickelt.",true,"Er schlug es 1989 vor."],
 ["allg","Die Fußball-Weltmeisterschaft 2018 gewann Deutschland.",false,"Weltmeister 2018 wurde Frankreich."],
 ["allg","Die Fußball-Weltmeisterschaft 2014 gewann Deutschland.",true,"Das Finale gegen Argentinien fand in Rio de Janeiro statt."],
 ["allg","Ein Marathon ist 42,195 Kilometer lang.",true,"Das ist die offizielle Streckenlänge."],
 ["allg","Ein Jahr hat genau 52 Wochen.",false,"Es sind 52 Wochen und ein bis zwei Tage."],
 ["allg","Die Zahl Pi ist eine rationale Zahl.",false,"Pi ist irrational, ihre Dezimalstellen wiederholen sich nie."],
 ["allg","Die Zahl 1 ist eine Primzahl.",false,"Eine Primzahl hat genau zwei Teiler, die 1 hat nur einen."],
 ["allg","Die 2 ist die einzige gerade Primzahl.",true,"Alle anderen geraden Zahlen sind durch 2 teilbar und haben daher mehr Teiler."],
 ["allg","Die Winkelsumme im Dreieck beträgt 180 Grad.",true,"Das gilt in der ebenen Geometrie."],
 ["allg","Ein Kilogramm Federn ist leichter als ein Kilogramm Steine.",false,"Beide wiegen ein Kilogramm."],
 ["allg","Die Olympischen Spiele 2024 fanden in Paris statt.",true,"Es waren die dritten Sommerspiele in Paris."],
 ["geo","Der Nil mündet ins Mittelmeer.",true,"Er fließt durch Ägypten und bildet dort ein großes Delta."],
 ["geo","Die Donau mündet ins Schwarze Meer.",true,"Sie durchfließt auf dem Weg mehrere Hauptstädte, etwa Wien, Budapest und Belgrad."],
 ["geo","Die Hauptstadt von Spanien ist Barcelona.",false,"Die Hauptstadt ist Madrid."],
 ["geo","Die Hauptstadt von Neuseeland ist Wellington.",true,"Größte Stadt des Landes ist aber Auckland."],
 ["geo","Der Mount Everest liegt an der Grenze zwischen Nepal und China.",true,"Er gehört zum Himalaya."],
 ["geo","Der Bodensee grenzt an Deutschland, Österreich und die Schweiz.",true,"Im Obersee ist der Grenzverlauf zwischen den drei Ländern nicht festgelegt."],
 ["geo","Das Matterhorn liegt in Frankreich.",false,"Das Matterhorn liegt an der Grenze zwischen der Schweiz und Italien."],
 ["geo","Der Ural gilt als Grenze zwischen Europa und Asien.",true,"Das Gebirge liegt in Russland und Kasachstan."],
 ["geo","Der Panamakanal verbindet den Atlantik mit dem Pazifik.",true,"Er wurde 1914 eröffnet."],
 ["geo","Die Hauptstadt von Schweden ist Helsinki.",false,"Die Hauptstadt von Schweden ist Stockholm, Helsinki ist die Hauptstadt von Finnland."],
 ["geo","Der Rhein mündet in die Nordsee.",true,"Seine Mündung liegt in den Niederlanden."],
 ["geo","Madagaskar ist eine Insel im Indischen Ozean.",true,"Sie liegt östlich von Afrika."],
 ["his","Der Erste Weltkrieg begann im Jahr 1914.",true,"Auslöser war das Attentat von Sarajevo im Juni 1914."],
 ["his","Der Bau der Berliner Mauer begann im Jahr 1961.",true,"Am 13. August 1961 wurde die Grenze abgeriegelt."],
 ["his","Die Bundesrepublik Deutschland wurde im Jahr 1949 gegründet.",true,"Im selben Jahr wurde auch die DDR gegründet."],
 ["his","Karl der Große wurde im Jahr 800 zum Kaiser gekrönt.",true,"Die Krönung fand an Weihnachten 800 in Rom statt."],
 ["his","Die Vereinigten Staaten erklärten im Jahr 1776 ihre Unabhängigkeit.",true,"Die Unabhängigkeitserklärung ist auf den 4. Juli 1776 datiert."],
 ["his","Konrad Adenauer war der erste Bundeskanzler der Bundesrepublik Deutschland.",true,"Er amtierte von 1949 bis 1963."],
 ["his","Angela Merkel war 16 Jahre lang Bundeskanzlerin.",true,"Sie war von 2005 bis 2021 im Amt."],
 ["his","Der Bundespräsident wird direkt vom Volk gewählt.",false,"Er wird von der Bundesversammlung gewählt."],
 ["his","Der Bundestag wird in der Regel alle vier Jahre gewählt.",true,"Die Wahlperiode dauert vier Jahre."],
 ["his","Martin Luther veröffentlichte im Jahr 1517 seine 95 Thesen.",true,"Der Thesenanschlag an der Wittenberger Schlosskirche gilt als Beginn der Reformation."],
 ["his","Das Deutsche Kaiserreich wurde im Jahr 1871 gegründet.",true,"Die Reichsgründung wurde in Versailles ausgerufen."],
 ["allg","Wolfgang Amadeus Mozart wurde in Salzburg geboren.",true,"Er kam 1756 dort zur Welt."],
 ["allg","Die Beatles kamen aus Liverpool.",true,"Die Band wurde dort in den 1960er-Jahren bekannt."],
 ["allg","Shakespeare schrieb Romeo und Julia.",true,"Das Stück wurde im 16. Jahrhundert geschrieben."],
 ["allg","Pablo Picasso wurde in Spanien geboren.",true,"Er kam in Málaga zur Welt und lebte später vor allem in Frankreich."],
 ["allg","Der Eiffelturm wurde für die Weltausstellung 1889 in Paris gebaut.",true,"Er wurde als temporäres Bauwerk geplant."],
 ["allg","Ein Fußballspiel dauert regulär 90 Minuten.",true,"Hinzu kommen Nachspielzeit und bei Bedarf Verlängerung."],
 ["allg","Im Basketball zählt ein Korb aus dem Feld immer drei Punkte.",false,"Ein normaler Korb zählt zwei Punkte, ein Dreier nur von hinter der Dreierlinie."],
 ["allg","Die Quadratwurzel von 144 ist 12.",true,"12 mal 12 ist 144."],
 ["allg","Ein Quadratmeter hat 100 Quadratzentimeter.",false,"Ein Quadratmeter hat 10.000 Quadratzentimeter."],
 ["allg","Ein Byte besteht aus 8 Bit.",true,"Das ist die gängige Definition."],
 ["allg","Steve Jobs gehörte zu den Gründern von Apple.",true,"Das Unternehmen wurde 1976 gegründet."],
 ["allg","Die erste Fußball-Weltmeisterschaft fand 1930 in Uruguay statt.",true,"Uruguay wurde auch erster Weltmeister."],
 ["allg","Ein Schachbrett hat 64 Felder.",true,"Es besteht aus 8 mal 8 Feldern."]
];
